### ISSUE TITLE
ENOENT: no such file or directory, open '/tmp/libreoffice-file-converter-21646-Jl56EzlszWHB/source.docx'

### ISSUE THREAD

**Issue by galaczi** [Girilloid/libreoffice-file-converter#1]
Hi, I am trying to convert from pdf to docx and getting this error. 

``ENOENT: no such file or directory, open '/tmp/libreoffice-file-converter-21646-Jl56EzlszWHB/source.docx'``

I know LibreOffice is capable of converting pdf to docx. I am also able to convert to html.

**Comment by Girilloid** [comment]
Hi, @galaczi!
I guess that issue here is related to file itself. LibreOffice is just failing to convert requested file and `convert` command failing to read result file since there is no file in temporary directory. Please check if result file is written to disk when `convertFile` command is executed.

**Comment by Girilloid** [comment]
Hi, @galaczi!
Now you can try to use newest version of the package [v2.1.0](https://github.com/Girilloid/libreoffice-file-converter/releases/tag/v2.1.0). Now it will throw original libreoffice error when tool fails to convert source file
