### ISSUE TITLE
Windows always get `Document is empty` error.

### ISSUE THREAD

**Issue by toknT** [Girilloid/libreoffice-file-converter#3]
This packge work well , on my wsl or server . However if on windows it get `error: Entity: line 1: parser error : Document is empty`.

I have installed libreoffice on windows side, and another package https://www.npmjs.com/package/libreoffice-convert work well too. But `libreoffice-convert` has no timeout option so when processing some malicious file uploaded by user , it become a hell

**Comment by Girilloid** [comment]
Hi, @toknT
Could you please specify your OS and LibreOffice version? Does this happen to any file you pass or just some of them?
I don't really use Windows for development, but I'll try to check what is wrong here. By the way it runs fine on github windows runners, so it might be difficult for me to reproduce the issue

**Comment by sugihartolim** [comment]
I can confirm that this error also happened on my windows dev machine running Windows 11 and LibreOffice Version: 24.2.4.2. 

> ERROR [ExceptionsHandler] Entity: line 1: parser error : Document is empty.

**Comment by saifurrehmanx** [comment]
I'm experiencing the same issue on Windows 11 while converting PPTX files to PDF. Despite trying multiple files, I encounter the same error:

`ERROR: Entity: line 1: parser error: Document is empty`

- **OS Name:** Microsoft Windows 11 Pro
- **OS Version:** 10.0.22631 Build 22631
- **LibreOffice:** v24.2.4.2 64bit

**Comment by Girilloid** [comment]
Ok, so the issue seems to be related to XML configuration parsing on win11. It doesn't show up on linux or even on github windows runners. Also I've checked **libreoffice-convert** behavior on win11 and I also get the same error. The only difference here is that **libreoffice-convert** silents all the errors that soffice binary produces.
The error doesn't affect convertation itself, so I just changed a way how errors are reconized (soffice also puts warnings into stderr and it's not a case to throw exception on any output here).
Here is a release which fixes the issue - https://github.com/Girilloid/libreoffice-file-converter/releases/tag/v2.3.1
